import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { Providers } from '../components/providers'
import './globals.css'

const opensans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={opensans.className}>{children}</body>
      </html>
    </Providers>
  )
}
